GET http://127.0.0.1:4000/api/users HTTP/1.1 

###
POST http://127.0.0.1:4000/api/users HTTP/1.1 
Content-Type: application/json

{
    "first_name": "Fernando",
    "last_name": "Guerrero",
    "email": "devvrior@mail.com",
    "password": "123",
    "address": "Calle ficticia 123",
    "is_admin": false
}

###
GET http://127.0.0.1:4000/api/games/ HTTP/1.1

###

POST http://127.0.0.1:4000/api/games HTTP/1.1 
Content-Type: application/json

{
    "title": "Gears 5",
    "game_type": "Shooter",
    "price":"1200",
    "clasification": "A18+",
    "image": "example/file3.png",
    "stock": 12
}

###

PUT http://127.0.0.1:4000/api/games/11 HTTP/1.1
Content-Type: application/json

{
    "title": "FIFA 20",
    "game_type": "Sports",
    "price":"1200",
    "clasification": "E10+",
    "image": "example/file2.png",
    "stock": 12
}

###
DELETE http://127.0.0.1:4000/api/games/1 HTTP/1.1


